In [1]:
import pandas as pd

# Vaccination Data Columns Definition
https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-Jurisdi/unsk-b7fc

In [2]:
# Vaccination Case USA
Vacc_Case_df = pd.read_csv('COVID-19_Vaccinations_in_the_United_States_Jurisdiction.csv')
Vacc_Case_df.head(5)

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Series_Complete_Pfizer_18Plus,Series_Complete_Unk_Manuf_18Plus,Series_Complete_Janssen_65Plus,Series_Complete_Moderna_65Plus,Series_Complete_Pfizer_65Plus,Series_Complete_Unk_Manuf_65Plus,Series_Complete_FedLTC,Series_Complete_FedLTC_Residents,Series_Complete_FedLTC_Staff,Series_Complete_FedLTC_Unknown
0,08/25/2021,34,DD2,4406980,186300,1852420,2368260,0,0,0,...,1041802,4,6879,51955,86404,0,0,0,0,0
1,08/25/2021,34,FM,80600,10200,68600,1800,0,77767,91064,...,82,1,949,1902,6,0,62,0,62,0
2,08/25/2021,34,NJ,12795445,606300,5165500,7023645,0,144057,167955,...,2628532,117,83036,585496,581977,37,112511,56224,46784,9503
3,08/25/2021,34,MT,1215235,69600,534940,610695,0,113703,132437,...,218985,234,8719,78476,75633,133,8764,4448,2900,1416
4,08/25/2021,34,MP,78180,2600,20200,55380,0,137442,160944,...,23653,0,81,449,2274,0,0,0,0,0

# Casae & Death Data Columns Definition
https://data.cdc.gov/Case-Surveillance/United-States-COVID-19-Cases-and-Deaths-by-State-o/9mfq-cb36

In [3]:
# Covid Cases and Deaths by State over time
Case_Death_df = pd.read_csv('United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv')
Case_Death_df.head(5)

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,created_at,consent_cases,consent_deaths
0,02/08/2020,AL,55,47.0,8.0,1,0.0,0,0.0,0.0,0,0.0,02/10/2020 12:00:00 AM,Agree,Agree
1,02/02/2021,IL,1130917,1130917.0,0.0,2304,0.0,21336,19306.0,2030.0,63,16.0,02/03/2021 02:55:58 PM,Agree,Agree
2,07/30/2020,ME,3910,3497.0,413.0,22,2.0,123,122.0,1.0,2,0.0,07/31/2020 02:35:06 PM,Agree,Agree
3,03/29/2020,AL,2634,2532.0,102.0,129,3.0,32,29.0,3.0,5,0.0,03/31/2020 12:00:00 AM,Agree,Agree
4,05/03/2020,NH,2518,NaN,NaN,89,0.0,86,NaN,NaN,2,0.0,05/04/2020 10:49:24 PM,Not agree,Not agree

In [4]:
# 5 States data filtered from Vaccination Data
Selected_States_Vacc_df = Vacc_Case_df.loc[(Vacc_Case_df["Location"] == "CA") |
                                 (Vacc_Case_df["Location"] == "TX") |
                                 (Vacc_Case_df["Location"] == "FL") |
                                 (Vacc_Case_df["Location"] == "CA") |
                                 (Vacc_Case_df["Location"] == "MO")
                                 ]
Selected_States_Vacc_df.sort_values(['Date'])
Selected_States_Vacc_df.head(5)

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Series_Complete_Pfizer_18Plus,Series_Complete_Unk_Manuf_18Plus,Series_Complete_Janssen_65Plus,Series_Complete_Moderna_65Plus,Series_Complete_Pfizer_65Plus,Series_Complete_Unk_Manuf_65Plus,Series_Complete_FedLTC,Series_Complete_FedLTC_Residents,Series_Complete_FedLTC_Staff,Series_Complete_FedLTC_Unknown
11,08/25/2021,34,FL,29353105,1694500,11670900,15987705,0,136668,157002,...,5468142,23279,192780,1792452,1671002,14838,174868,89995,50923,33950
25,08/25/2021,34,CA,53846465,2615800,21594880,29635785,0,136278,160037,...,10430577,3521,176026,2331048,2076790,1226,360776,171926,161640,27210
38,08/25/2021,34,TX,36920965,1894600,14616960,20409405,0,127332,153192,...,6710452,693,246420,1092418,1556089,161,199271,96080,67092,36099
42,08/25/2021,34,MO,7120835,311400,2885480,3923955,0,116023,136005,...,1414121,145,36214,370710,404747,62,65532,37029,20766,7737
82,08/24/2021,34,TX,36739015,1894600,14475420,20368995,0,126704,152437,...,6676995,693,245264,1090038,1547424,161,199266,96079,67088,36099

In [15]:
# Check Data Types
Selected_States_Vacc_df.dtypes

Date                                object
MMWR_week                            int64
Location                            object
Distributed                          int64
Distributed_Janssen                  int64
                                     ...
Series_Complete_Unk_Manuf_65Plus     int64
Series_Complete_FedLTC               int64
Series_Complete_FedLTC_Residents     int64
Series_Complete_FedLTC_Staff         int64
Series_Complete_FedLTC_Unknown       int64
Length: 69, dtype: object

In [8]:
# Check any missing value
Selected_States_Vacc_df.isnull().sum()

Date                                0
MMWR_week                           0
Location                            0
Distributed                         0
Distributed_Janssen                 0
                                   ..
Series_Complete_Unk_Manuf_65Plus    0
Series_Complete_FedLTC              0
Series_Complete_FedLTC_Residents    0
Series_Complete_FedLTC_Staff        0
Series_Complete_FedLTC_Unknown      0
Length: 69, dtype: int64

In [5]:
# 5 States data filtered from Case & Death Data
Selected_States_Case_Death_df = Case_Death_df.loc[(Case_Death_df["state"] == "CA") |
                                 (Case_Death_df["state"] == "TX") |
                                 (Case_Death_df["state"] == "FL") |
                                 (Case_Death_df["state"] == "CA") |
                                 (Case_Death_df["state"] == "MO")
                                 ]
Selected_States_Case_Death_df.sort_values(['submission_date'])
Selected_States_Case_Death_df.head(5)

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,created_at,consent_cases,consent_deaths
12,09/13/2020,MO,108944,NaN,NaN,663,18.0,2132,NaN,NaN,19,0.0,09/15/2020 12:00:00 AM,Not agree,Not agree
23,07/09/2021,MO,631603,NaN,NaN,1639,472.0,9387,NaN,NaN,4,0.0,07/10/2021 02:17:36 PM,Not agree,Not agree
25,10/28/2020,MO,194250,NaN,NaN,3507,304.0,3389,NaN,NaN,32,0.0,10/30/2020 12:00:00 AM,Not agree,Not agree
32,02/24/2020,MO,0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,03/26/2020 04:22:39 PM,Not agree,Not agree
34,02/11/2021,MO,540239,NaN,NaN,1007,270.0,8330,NaN,NaN,19,0.0,02/13/2021 12:00:00 AM,Not agree,Not agree

In [18]:
# Check Data Types
Selected_States_Case_Death_df.dtypes

submission_date    datetime64[ns]
state                      object
tot_cases                   int64
conf_cases                float64
prob_cases                float64
new_case                    int64
pnew_case                 float64
tot_death                   int64
conf_death                float64
prob_death                float64
new_death                   int64
pnew_death                float64
created_at                 object
consent_cases              object
consent_deaths             object
dtype: object

In [19]:
# Check any missing value
Selected_States_Case_Death_df.isnull().sum()

submission_date       0
state                 0
tot_cases             0
conf_cases         1757
prob_cases         1757
new_case              0
pnew_case           134
tot_death             0
conf_death         1757
prob_death         1757
new_death             0
pnew_death          134
created_at            0
consent_cases         0
consent_deaths        0
dtype: int64